// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.3
// source: proto/streams.proto

package go_streams_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	RandomNumbers(ctx context.Context, in *RandomNumRequest, opts ...grpc.CallOption) (DataService_RandomNumbersClient, error)
	SumNumbers(ctx context.Context, opts ...grpc.CallOption) (DataService_SumNumbersClient, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) RandomNumbers(ctx context.Context, in *RandomNumRequest, opts ...grpc.CallOption) (DataService_RandomNumbersClient, error) {
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[0], "/streams.DataService/RandomNumbers", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataServiceRandomNumbersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DataService_RandomNumbersClient interface {
	Recv() (*RandomNumResponse, error)
	grpc.ClientStream
}

type dataServiceRandomNumbersClient struct {
	grpc.ClientStream
}

func (x *dataServiceRandomNumbersClient) Recv() (*RandomNumResponse, error) {
	m := new(RandomNumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataServiceClient) SumNumbers(ctx context.Context, opts ...grpc.CallOption) (DataService_SumNumbersClient, error) {
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[1], "/streams.DataService/SumNumbers", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataServiceSumNumbersClient{stream}
	return x, nil
}

type DataService_SumNumbersClient interface {
	Send(*SumNumRequest) error
	CloseAndRecv() (*SumNumResponse, error)
	grpc.ClientStream
}

type dataServiceSumNumbersClient struct {
	grpc.ClientStream
}

func (x *dataServiceSumNumbersClient) Send(m *SumNumRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataServiceSumNumbersClient) CloseAndRecv() (*SumNumResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SumNumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility
type DataServiceServer interface {
	RandomNumbers(*RandomNumRequest, DataService_RandomNumbersServer) error
	SumNumbers(DataService_SumNumbersServer) error
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataServiceServer struct {
}

func (UnimplementedDataServiceServer) RandomNumbers(*RandomNumRequest, DataService_RandomNumbersServer) error {
	return status.Errorf(codes.Unimplemented, "method RandomNumbers not implemented")
}
func (UnimplementedDataServiceServer) SumNumbers(DataService_SumNumbersServer) error {
	return status.Errorf(codes.Unimplemented, "method SumNumbers not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_RandomNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RandomNumRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServiceServer).RandomNumbers(m, &dataServiceRandomNumbersServer{stream})
}

type DataService_RandomNumbersServer interface {
	Send(*RandomNumResponse) error
	grpc.ServerStream
}

type dataServiceRandomNumbersServer struct {
	grpc.ServerStream
}

func (x *dataServiceRandomNumbersServer) Send(m *RandomNumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DataService_SumNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServiceServer).SumNumbers(&dataServiceSumNumbersServer{stream})
}

type DataService_SumNumbersServer interface {
	SendAndClose(*SumNumResponse) error
	Recv() (*SumNumRequest, error)
	grpc.ServerStream
}

type dataServiceSumNumbersServer struct {
	grpc.ServerStream
}

func (x *dataServiceSumNumbersServer) SendAndClose(m *SumNumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataServiceSumNumbersServer) Recv() (*SumNumRequest, error) {
	m := new(SumNumRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streams.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RandomNumbers",
			Handler:       _DataService_RandomNumbers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SumNumbers",
			Handler:       _DataService_SumNumbers_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/streams.proto",
}
