// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: proto/streams.proto

package go_streams_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RandomNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count    int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	IsRange  bool  `protobuf:"varint,2,opt,name=isRange,proto3" json:"isRange,omitempty"`
	MinValue int64 `protobuf:"varint,3,opt,name=minValue,proto3" json:"minValue,omitempty"`
	MaxValue int64 `protobuf:"varint,4,opt,name=maxValue,proto3" json:"maxValue,omitempty"`
}

func (x *RandomNumRequest) Reset() {
	*x = RandomNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_streams_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomNumRequest) ProtoMessage() {}

func (x *RandomNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streams_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomNumRequest.ProtoReflect.Descriptor instead.
func (*RandomNumRequest) Descriptor() ([]byte, []int) {
	return file_proto_streams_proto_rawDescGZIP(), []int{0}
}

func (x *RandomNumRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RandomNumRequest) GetIsRange() bool {
	if x != nil {
		return x.IsRange
	}
	return false
}

func (x *RandomNumRequest) GetMinValue() int64 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *RandomNumRequest) GetMaxValue() int64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

type RandomNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RandomNumResponse) Reset() {
	*x = RandomNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_streams_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomNumResponse) ProtoMessage() {}

func (x *RandomNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streams_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomNumResponse.ProtoReflect.Descriptor instead.
func (*RandomNumResponse) Descriptor() ([]byte, []int) {
	return file_proto_streams_proto_rawDescGZIP(), []int{1}
}

func (x *RandomNumResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SumNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SumNumRequest) Reset() {
	*x = SumNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_streams_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumNumRequest) ProtoMessage() {}

func (x *SumNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streams_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumNumRequest.ProtoReflect.Descriptor instead.
func (*SumNumRequest) Descriptor() ([]byte, []int) {
	return file_proto_streams_proto_rawDescGZIP(), []int{2}
}

func (x *SumNumRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SumNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *SumNumResponse) Reset() {
	*x = SumNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_streams_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumNumResponse) ProtoMessage() {}

func (x *SumNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_streams_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumNumResponse.ProtoReflect.Descriptor instead.
func (*SumNumResponse) Descriptor() ([]byte, []int) {
	return file_proto_streams_proto_rawDescGZIP(), []int{3}
}

func (x *SumNumResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_streams_proto protoreflect.FileDescriptor

var file_proto_streams_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x22, 0x7a,
	0x0a, 0x10, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x61, 0x78, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x6d, 0x61, 0x78, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x29, 0x0a, 0x11, 0x52, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x53, 0x75, 0x6d, 0x4e, 0x75, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x26, 0x0a, 0x0e,
	0x53, 0x75, 0x6d, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x32, 0x98, 0x01, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2e,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x3f,
	0x0a, 0x0a, 0x53, 0x75, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x53, 0x75, 0x6d, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x53,
	0x75, 0x6d, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x42,
	0x2d, 0x5a, 0x2b, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x6f, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x67,
	0x6f, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_streams_proto_rawDescOnce sync.Once
	file_proto_streams_proto_rawDescData = file_proto_streams_proto_rawDesc
)

func file_proto_streams_proto_rawDescGZIP() []byte {
	file_proto_streams_proto_rawDescOnce.Do(func() {
		file_proto_streams_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_streams_proto_rawDescData)
	})
	return file_proto_streams_proto_rawDescData
}

var file_proto_streams_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_streams_proto_goTypes = []interface{}{
	(*RandomNumRequest)(nil),  // 0: streams.RandomNumRequest
	(*RandomNumResponse)(nil), // 1: streams.RandomNumResponse
	(*SumNumRequest)(nil),     // 2: streams.SumNumRequest
	(*SumNumResponse)(nil),    // 3: streams.SumNumResponse
}
var file_proto_streams_proto_depIdxs = []int32{
	0, // 0: streams.DataService.RandomNumbers:input_type -> streams.RandomNumRequest
	2, // 1: streams.DataService.SumNumbers:input_type -> streams.SumNumRequest
	1, // 2: streams.DataService.RandomNumbers:output_type -> streams.RandomNumResponse
	3, // 3: streams.DataService.SumNumbers:output_type -> streams.SumNumResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_streams_proto_init() }
func file_proto_streams_proto_init() {
	if File_proto_streams_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_streams_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_streams_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_streams_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_streams_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_streams_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_streams_proto_goTypes,
		DependencyIndexes: file_proto_streams_proto_depIdxs,
		MessageInfos:      file_proto_streams_proto_msgTypes,
	}.Build()
	File_proto_streams_proto = out.File
	file_proto_streams_proto_rawDesc = nil
	file_proto_streams_proto_goTypes = nil
	file_proto_streams_proto_depIdxs = nil
}
